# Random_Forest_Regression_Case_Study - 28


## Load the data set petrol_consumption.csv. 

## Use Decision Tree and Random Forest algorithms to predict Petrol_Consumption



### Import Libraries

In [1]:
import os 
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### Importing Dataset

In [28]:
os.chdir('C:\\Users\\ankit\\OneDrive\\Documents\\Desktop\\DATA SCIENCE\\Top Mentor Lecture\\24_Day_31_7_21\\Case Studies with Answer\\CS 28 Ans- Random Forest Regression')
df = pd.read_csv('petrol_consumption.csv')
df

Petrol_tax  Average_income  Paved_Highways  Population_Driver_licence(%)  \
0         9.00            3571            1976                         0.525   
1         9.00            4092            1250                         0.572   
2         9.00            3865            1586                         0.580   
3         7.50            4870            2351                         0.529   
4         8.00            4399             431                         0.544   
5        10.00            5342            1333                         0.571   
6         8.00            5319           11868                         0.451   
7         8.00            5126            2138                         0.553   
8         8.00            4447            8577                         0.529   
9         7.00            4512            8507                         0.552   
10        8.00            4391            5939                         0.530   
11        7.50            5126           14186                         0.525   
12        7.00            4817            6930                         0.574   
13        7.00            4207            6580                         0.545   
14        7.00            4332            8159                         0.608   
15        7.00            4318           10340                         0.586   
16        7.00            4206            8508                         0.572   
17        7.00            3718            4725                         0.540   
18        7.00            4716            5915                         0.724   
19        8.50            4341            6010                         0.677   
20        7.00            4593            7834                         0.663   
21        8.00            4983             602                         0.602   
22        9.00            4897            2449                         0.511   
23        9.00            4258            4686                         0.517   
24        8.50            4574            2619                         0.551   
25        9.00            3721            4746                         0.544   
26        8.00            3448            5399                         0.548   
27        7.50            3846            9061                         0.579   
28        8.00            4188            5975                         0.563   
29        9.00            3601            4650                         0.493   
30        7.00            3640            6905                         0.518   
31        7.00            3333            6594                         0.513   
32        8.00            3063            6524                         0.578   
33        7.50            3357            4121                         0.547   
34        8.00            3528            3495                         0.487   
35        6.58            3802            7834                         0.629   
36        5.00            4045           17782                         0.566   
37        7.00            3897            6385                         0.586   
38        8.50            3635            3274                         0.663   
39        7.00            4345            3905                         0.672   
40        7.00            4449            4639                         0.626   
41        7.00            3656            3985                         0.563   
42        7.00            4300            3635                         0.603   
43        7.00            3745            2611                         0.508   
44        6.00            5215            2302                         0.672   
45        9.00            4476            3942                         0.571   
46        7.00            4296            4083                         0.623   
47        7.00            5002            9794                         0.593   

    Petrol_Consumption  
0                  541  
1                  524  
2       

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 5 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Petrol_tax                    48 non-null     float64
 1   Average_income                48 non-null     int64  
 2   Paved_Highways                48 non-null     int64  
 3   Population_Driver_licence(%)  48 non-null     float64
 4   Petrol_Consumption            48 non-null     int64  
dtypes: float64(2), int64(3)
memory usage: 2.0 KB


In [4]:
df.describe()

Petrol_tax  Average_income  Paved_Highways  \
count   48.000000       48.000000       48.000000   
mean     7.668333     4241.833333     5565.416667   
std      0.950770      573.623768     3491.507166   
min      5.000000     3063.000000      431.000000   
25%      7.000000     3739.000000     3110.250000   
50%      7.500000     4298.000000     4735.500000   
75%      8.125000     4578.750000     7156.000000   
max     10.000000     5342.000000    17782.000000   

       Population_Driver_licence(%)  Petrol_Consumption  
count                     48.000000           48.000000  
mean                       0.570333          576.770833  
std                        0.055470          111.885816  
min                        0.451000          344.000000  
25%                        0.529750          509.500000  
50%                        0.564500          568.500000  
75%                        0.595250          632.750000  
max                        0.724000          968.000000

### Create X – variable

In [30]:
X = df.iloc[:, 0:4].values
print(X)

[[9.0000e+00 3.5710e+03 1.9760e+03 5.2500e-01]
 [9.0000e+00 4.0920e+03 1.2500e+03 5.7200e-01]
 [9.0000e+00 3.8650e+03 1.5860e+03 5.8000e-01]
 [7.5000e+00 4.8700e+03 2.3510e+03 5.2900e-01]
 [8.0000e+00 4.3990e+03 4.3100e+02 5.4400e-01]
 [1.0000e+01 5.3420e+03 1.3330e+03 5.7100e-01]
 [8.0000e+00 5.3190e+03 1.1868e+04 4.5100e-01]
 [8.0000e+00 5.1260e+03 2.1380e+03 5.5300e-01]
 [8.0000e+00 4.4470e+03 8.5770e+03 5.2900e-01]
 [7.0000e+00 4.5120e+03 8.5070e+03 5.5200e-01]
 [8.0000e+00 4.3910e+03 5.9390e+03 5.3000e-01]
 [7.5000e+00 5.1260e+03 1.4186e+04 5.2500e-01]
 [7.0000e+00 4.8170e+03 6.9300e+03 5.7400e-01]
 [7.0000e+00 4.2070e+03 6.5800e+03 5.4500e-01]
 [7.0000e+00 4.3320e+03 8.1590e+03 6.0800e-01]
 [7.0000e+00 4.3180e+03 1.0340e+04 5.8600e-01]
 [7.0000e+00 4.2060e+03 8.5080e+03 5.7200e-01]
 [7.0000e+00 3.7180e+03 4.7250e+03 5.4000e-01]
 [7.0000e+00 4.7160e+03 5.9150e+03 7.2400e-01]
 [8.5000e+00 4.3410e+03 6.0100e+03 6.7700e-01]
 [7.0000e+00 4.5930e+03 7.8340e+03 6.6300e-01]
 [8.0000e+00 

In [29]:
y = df.iloc[:, 4].values
print(y)

[541 524 561 414 410 457 344 467 464 498 580 471 525 508 566 635 603 714
 865 640 649 540 464 547 460 566 577 631 574 534 571 554 577 628 487 644
 640 704 648 968 587 699 632 591 782 510 610 524]


### Train Test Split 

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print('Shape of X train {}'.format(X_train.shape), "&", 'Shape of y_train {}'.format(y_train.shape))
print('Shape of X_train {}'.format(X_test.shape), '&', 'Shape of y_test {}'.format(y_test.shape))

Shape of X train (38, 4) & Shape of y_train (38,)
Shape of X_train (10, 4) & Shape of y_test (10,)


### Feature Scaling  

In [22]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
print('X train after standerd scaler : \n ',(X_test[0:5]),'\n')
print('X test after standerd scaler : \n ',(X_train[0:5]))

X train after standerd scaler : 
  [[ 2.00000000e+00 -5.99985703e-01 -2.52300440e-04 -1.31574460e+00]
 [ 3.33333333e-01  7.55587884e-01 -2.12916342e+00 -5.67769713e-02]
 [ 3.33333333e-01 -8.59888909e-01  3.77693759e-01  4.19655875e-02]
 [-1.33333333e+00 -5.33735866e-01  1.13762269e+00 -6.98603604e-01]
 [ 3.33333333e-01 -1.51389371e+00  9.45369750e-01  7.82534779e-01]] 

X test after standerd scaler : 
  [[-0.13252569  1.50577399  2.25854636 -0.91579106]
 [-0.62819265 -1.83367022  0.21233384 -1.12852703]
 [-0.13252569 -1.78897047 -0.45419455 -0.5257751 ]
 [-0.13252569 -0.87821295  0.8772451   0.04152084]
 [-0.62819265  1.27482526  1.07480487  0.28971281]]


### Create Model   

In [23]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators = 20, random_state = 0)
regressor.fit(X_train,y_train)


RandomForestRegressor(n_estimators=20, random_state=0)

### Prediction

In [24]:
y_pred = regressor.predict(X_test)
y_pred

array([554.45, 511.45, 590.1 , 599.5 , 625.6 , 617.75, 571.2 , 750.85,
       507.7 , 482.65])

### Evaluate Error   

In [26]:
from sklearn import metrics

In [27]:
print('Mean Absolute Error : ', metrics.median_absolute_error(y_test, y_pred))
print('Mean Squared Error : ', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error : ', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error :  66.40000000000003
Mean Squared Error :  6656.516250000002
Root Mean Squared Error :  81.58747606097398
