# 4. Supervised_Learning_Case_Study - 33

## Case Study

### Domain – Media

### Focus – Optimize Selection Process


### Business Challenge / Requirement

Motion Studios is the largest Radio production house in Europe. Their total revenue $ 1B+. Company has launched a new reality  show – "The Star RJ". The show is about finding a new Radio Jockey who will be the star presenter on upcoming shows.

In first round participants have to upload their voice clip online and the clip will be evaluated by experts for selection into the next round. There is a separate team in the first round for evaluation of male and female voice.

Response to the show is unprecedented and company is flooded with voice clips.

You as a ML expert have to classify the voice as either male/female so that first level of filtration is quicker.

Key issues
Voice sample are across accents

### Data volume

- Approx 3000 records – file **voice-classification.csv** Fields in Data

- meanfreq: mean frequency (in kHz)

- sd: standard deviation of frequency

- median: median frequency (in kHz)

- Q25: first quantile (in kHz)

- Q75: third quantile (in kHz)

- IQR: interquantile range (in kHz)

- skew: skewness (see note in specprop description)

- kurt: kurtosis (see note in specprop description)

- sp.ent: spectral entropy

- sfm: spectral flatness

- mode: mode frequency

- centroid: frequency centroid (see specprop)

- peakf: peak frequency (frequency with highest energy)

- meanfun: average of fundamental frequency measured across acoustic signal

- minfun: minimum fundamental frequency measured across acoustic signal

- maxfun: maximum fundamental frequency measured across acoustic signal

- meandom: average of dominant frequency measured across acoustic signal

- mindom: minimum of dominant frequency measured across acoustic signal

- maxdom: maximum of dominant frequency measured across acoustic signal

- dfrange: range of dominant frequency measured across acoustic signal

- modindx: modulation index. Calculated as the accumulated absolute difference between adjacent measurements of fundamental frequencies divided by the frequency range

- label: male or female




### Additional information
- NA



### Business benefits

Since "The Star RJ" is a reality show, time to select candidates is very short. The whole success of the show and hence the profits depends upon quick and smooth execution

##### Note: Use SVM , Naïve Bayce  and GridSearchCV to classify the data 


### Import Libraries

In [1]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

### Load Dataset

In [2]:
os.chdir('C:\\Users\\ankit\\OneDrive\\Documents\\Desktop\\DATA SCIENCE\\Top Mentor Lecture\\24_Day_31_7_21\\Case Studies with Answer\\CS 33 Ans -Supervised Learnig-4')
df = pd.read_csv('voice-classification.csv')
df.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

### Data Check

In [4]:
df.shape

(3168, 21)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3168 entries, 0 to 3167
Data columns (total 21 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   meanfreq  3168 non-null   float64
 1   sd        3168 non-null   float64
 2   median    3168 non-null   float64
 3   Q25       3168 non-null   float64
 4   Q75       3168 non-null   float64
 5   IQR       3168 non-null   float64
 6   skew      3168 non-null   float64
 7   kurt      3168 non-null   float64
 8   sp.ent    3168 non-null   float64
 9   sfm       3168 non-null   float64
 10  mode      3168 non-null   float64
 11  centroid  3168 non-null   float64
 12  meanfun   3168 non-null   float64
 13  minfun    3168 non-null   float64
 14  maxfun    3168 non-null   float64
 15  meandom   3168 non-null   float64
 16  mindom    3168 non-null   float64
 17  maxdom    3168 non-null   float64
 18  dfrange   3168 non-null   float64
 19  modindx   3168 non-null   float64
 20  label     3168 non-null   obje

In [13]:
df.describe().T

count       mean         std       min       25%       50%  \
meanfreq  3168.0   0.180907    0.029918  0.039363  0.163662  0.184838   
sd        3168.0   0.057126    0.016652  0.018363  0.041954  0.059155   
median    3168.0   0.185621    0.036360  0.010975  0.169593  0.190032   
Q25       3168.0   0.140456    0.048680  0.000229  0.111087  0.140286   
Q75       3168.0   0.224765    0.023639  0.042946  0.208747  0.225684   
IQR       3168.0   0.084309    0.042783  0.014558  0.042560  0.094280   
skew      3168.0   3.140168    4.240529  0.141735  1.649569  2.197101   
kurt      3168.0  36.568461  134.928661  2.068455  5.669547  8.318463   
sp.ent    3168.0   0.895127    0.044980  0.738651  0.861811  0.901767   
sfm       3168.0   0.408216    0.177521  0.036876  0.258041  0.396335   
mode      3168.0   0.165282    0.077203  0.000000  0.118016  0.186599   
centroid  3168.0   0.180907    0.029918  0.039363  0.163662  0.184838   
meanfun   3168.0   0.142807    0.032304  0.055565  0.116998  0.140519   
minfun    3168.0   0.036802    0.019220  0.009775  0.018223  0.046110   
maxfun    3168.0   0.258842    0.030077  0.103093  0.253968  0.271186   
meandom   3168.0   0.829211    0.525205  0.007812  0.419828  0.765795   
mindom    3168.0   0.052647    0.063299  0.004883  0.007812  0.023438   
maxdom    3168.0   5.047277    3.521157  0.007812  2.070312  4.992188   
dfrange   3168.0   4.994630    3.520039  0.000000  2.044922  4.945312   
modindx   3168.0   0.173752    0.119454  0.000000  0.099766  0.139357   

                75%          max  
meanfreq   0.199146     0.251124  
sd         0.067020     0.115273  
median     0.210618     0.261224  
Q25        0.175939     0.247347  
Q75        0.243660     0.273469  
IQR        0.114175     0.252225  
skew       2.931694    34.725453  
kurt      13.648905  1309.612887  
sp.ent     0.928713     0.981997  
sfm        0.533676     0.842936  
mode       0.221104     0.280000  
centroid   0.199146     0.251124  
meanfun    0.169581     0.237636  
minfun     0.047904     0.204082  
maxfun     0.277457     0.279114  
meandom    1.177166     2.957682  
mindom     0.070312     0.458984  
maxdom     7.007812    21.867188  
dfrange    6.992188    21.843750  
modindx    0.209183     0.932374

In [14]:
df.isnull().sum()

meanfreq    0
sd          0
median      0
Q25         0
Q75         0
IQR         0
skew        0
kurt        0
sp.ent      0
sfm         0
mode        0
centroid    0
meanfun     0
minfun      0
maxfun      0
meandom     0
mindom      0
maxdom      0
dfrange     0
modindx     0
label       0
dtype: int64

In [20]:
print('Shape of Data :')
print('Data set have',df.shape[0], 'Rows and', df.shape[1], 'Columns')

Shape of Data :
Data set have 3168 Rows and 21 Columns


In [22]:
print('Total number of labels : {}'.format(df.shape[0]))

Total number of labels : 3168


In [30]:
print('Total number of Male : {}'.format(df[df.label == 'male'].shape[0]))

Total number of Male : 1584


In [32]:
print('Total number of Female : {}'.format(df[df['label'] == 'female'].shape[0]))

Total number of Female : 1584


### Creat X

In [40]:
X = df.iloc[:, :-1].values
X[0:5]

array([[5.97809850e-02, 6.42412677e-02, 3.20269134e-02, 1.50714886e-02,
        9.01934399e-02, 7.51219512e-02, 1.28634618e+01, 2.74402906e+02,
        8.93369417e-01, 4.91917766e-01, 0.00000000e+00, 5.97809850e-02,
        8.42791064e-02, 1.57016683e-02, 2.75862069e-01, 7.81250000e-03,
        7.81250000e-03, 7.81250000e-03, 0.00000000e+00, 0.00000000e+00],
       [6.60087404e-02, 6.73100288e-02, 4.02287348e-02, 1.94138670e-02,
        9.26661901e-02, 7.32523231e-02, 2.24232854e+01, 6.34613855e+02,
        8.92193242e-01, 5.13723843e-01, 0.00000000e+00, 6.60087404e-02,
        1.07936554e-01, 1.58259149e-02, 2.50000000e-01, 9.01442308e-03,
        7.81250000e-03, 5.46875000e-02, 4.68750000e-02, 5.26315789e-02],
       [7.73155027e-02, 8.38294209e-02, 3.67184587e-02, 8.70105656e-03,
        1.31908017e-01, 1.23206961e-01, 3.07571546e+01, 1.02492770e+03,
        8.46389092e-01, 4.78904979e-01, 0.00000000e+00, 7.73155027e-02,
        9.87062616e-02, 1.56555773e-02, 2.71186441e-01, 7.9900

In [41]:
y = df.iloc[:, -1]
y[0:5]

0    male
1    male
2    male
3    male
4    male
Name: label, dtype: object

### Label Encoder

In [42]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y = encoder.fit_transform(y)
y[0:5]

array([1, 1, 1, 1, 1])

### Standardization

In [46]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)
X

array([[-4.04924806,  0.4273553 , -4.22490077, ..., -1.43142165,
        -1.41913712, -1.45477229],
       [-3.84105325,  0.6116695 , -3.99929342, ..., -1.41810716,
        -1.4058184 , -1.01410294],
       [-3.46306647,  1.60384791, -4.09585052, ..., -1.42920257,
        -1.41691733, -1.06534356],
       ...,
       [-1.29877326,  2.32272355, -0.05197279, ..., -0.5992661 ,
        -0.58671739,  0.17588664],
       [-1.2452018 ,  2.012196  , -0.01772849, ..., -0.41286326,
        -0.40025537,  1.14916112],
       [-0.51474626,  2.14765111, -0.07087873, ..., -1.27608595,
        -1.2637521 ,  1.47567886]])

### Train Test Split

In [47]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 100)

In [51]:
print('X train :{}'.format(X_train.shape),'and X test :{}'.format(X_test.shape))
print('y train :{}'.format(y_train.shape),'and y test :{}'.format(y_test.shape))

X train :(2217, 20) and X test :(951, 20)
y train :(2217,) and y test :(951,)


# Support Vector Machine 

In [52]:
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix

In [55]:
svc_model = SVC()
svc_model.fit(X_train, y_train)
print('svc model fitted successfully')

svc model fitted successfully


### Prediction

In [56]:
y_pred = svc_model.predict(X_test)
print('Prediction done successfully')

Prediction done successfully


### Accuracy Score

In [57]:
metrics.accuracy_score(y_pred, y_test)

0.9737118822292324

In [59]:
svc_model.score(X_train, y_train)

0.9869192602616148

In [61]:
svc_model.score(X_test, y_test)

0.9737118822292324

### Confusion Matrix

In [63]:
print(metrics.confusion_matrix(y_pred, y_test))

[[458  12]
 [ 13 468]]


### Classification Report

In [64]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97       470
           1       0.97      0.97      0.97       481

    accuracy                           0.97       951
   macro avg       0.97      0.97      0.97       951
weighted avg       0.97      0.97      0.97       951



## Cross Validation 

### GridSearch CV

In [67]:
from sklearn.model_selection import GridSearchCV

param_grid = {'C' : [0.1, 1, 10, 100], 'gamma' : [1, 0.1, 0.01, 0.001]}
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 2)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] END .....................................C=0.1, gamma=1; total time=   0.3s
[CV] END .....................................C=0.1, gamma=1; total time=   0.2s
[CV] END .....................................C=0.1, gamma=1; total time=   0.2s
[CV] END .....................................C=0.1, gamma=1; total time=   0.3s
[CV] END .....................................C=0.1, gamma=1; total time=   0.2s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.1s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.1s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.1s
[CV] END ..................................C=0.1, gamma=0.01; total time=   0.1s
[CV] END ..................................C=0.1

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001]},
             verbose=2)

### Print Best paraameters

In [68]:
best_params = grid.best_params_
print(best_params)

{'C': 1, 'gamma': 0.1}


### Predictions

In [70]:
grid_prediction = grid.predict(X_test)

### Accuracy score

In [71]:
print('Accuracy Score')
print(metrics.accuracy_score(grid_prediction, y_test))

Accuracy Score
0.9747634069400631


### Classification Report

In [73]:
print(classification_report(grid_prediction, y_test))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97       471
           1       0.97      0.97      0.97       480

    accuracy                           0.97       951
   macro avg       0.97      0.97      0.97       951
weighted avg       0.97      0.97      0.97       951



# Naïve Bayce GaussianNB

In [96]:
from sklearn.naive_bayes import GaussianNB

GNB = GaussianNB()
GNB.fit(X_train, y_train)
print('GaussianNB model fited succussfuly')

GaussianNB model fited succussfuly


### Prediction

In [97]:
GNB_pred = GNB.predict(X_test)
print("Prediction done succussfully")
print(GNB_pred)

Prediction done succussfully
[1 0 1 0 0 0 0 0 1 1 1 0 1 0 0 1 0 1 1 0 1 0 0 0 0 1 1 1 0 1 1 0 0 0 0 1 0
 0 1 1 0 1 1 1 0 0 1 0 0 1 1 0 0 0 0 1 0 1 1 1 1 0 1 0 0 0 1 1 0 1 0 1 1 1
 1 1 0 0 1 0 0 1 1 0 1 0 1 0 0 0 0 1 1 0 1 1 1 1 0 0 0 0 1 1 0 1 0 1 0 0 0
 0 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 1 1 1
 0 1 0 0 1 1 0 0 0 0 1 0 1 1 1 0 0 1 0 1 0 0 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0
 1 0 0 0 0 0 1 0 0 0 1 1 0 1 0 1 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 1 1
 0 0 1 0 0 1 1 1 1 1 1 1 0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 1 1 0 1 0 0 0 0 0 0
 1 1 1 0 1 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 1 0
 1 1 0 1 1 0 0 0 1 1 0 1 0 0 1 1 0 1 0 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 1 1 1
 0 1 0 0 0 1 1 0 0 1 1 0 1 0 0 1 0 1 1 0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 0 0
 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 1 1 1 0 1 1 0 1 0 0 1 0 1 1 1 0 0 1 1 0 1 0
 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 1
 0 1 1 1 0 0 1 0 1 1 0 0 0 1 1 1 1 0 0 0 1 0 0 1 0 1 0 1 1 0 0 0 1 0 1 

In [92]:
print(pd.DataFrame(GNB_pred).groupby(0).agg({0:np.size}))

     0
0     
0  465
1  486


In [93]:
print('Accuracy Score')
print(metrics.accuracy_score(y_test, GBN_pred))

Accuracy Score
0.8696109358569927


In [94]:
print('Classification Report')
print(classification_report(y_test, GBN_pred))

Classification Report
              precision    recall  f1-score   support

           0       0.87      0.86      0.87       471
           1       0.87      0.88      0.87       480

    accuracy                           0.87       951
   macro avg       0.87      0.87      0.87       951
weighted avg       0.87      0.87      0.87       951



In [86]:
print('Confusion Matrix')
print(confusion_matrix(y_test, GBN_pred))

Confusion Matrix
[[406  65]
 [ 59 421]]


### Apply Grid Search CV  for Naïve Bayce 

In [102]:
from sklearn.model_selection import GridSearchCV
param_grid = {} 
grid = GridSearchCV(GaussianNB(),param_grid,refit=True,verbose=2)
grid.fit(X_train,y_train)


Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV] END .................................................... total time=   0.0s
[CV] END .................................................... total time=   0.0s
[CV] END .................................................... total time=   0.0s
[CV] END .................................................... total time=   0.0s
[CV] END .................................................... total time=   0.0s


GridSearchCV(estimator=GaussianNB(), param_grid={}, verbose=2)

### Best Parameters

In [103]:
best_params = grid.best_params_
print(best_params)

{}


### Prediction

In [105]:
grid_prediction = grid.predict(X_test)

### Accuracy Score

In [108]:
print('Accuracy Score')
print(metrics.accuracy_score(y_test, grid_prediction))

Accuracy Score
0.8696109358569927


### Classification Report

In [109]:
print('Classification Report')
print(metrics.classification_report(y_test, grid_prediction))

Classification Report
              precision    recall  f1-score   support

           0       0.87      0.86      0.87       471
           1       0.87      0.88      0.87       480

    accuracy                           0.87       951
   macro avg       0.87      0.87      0.87       951
weighted avg       0.87      0.87      0.87       951



### Confusion Martix

In [110]:
print('Confusion Matrix')
print(metrics.confusion_matrix(y_test, grid_prediction))

Confusion Matrix
[[406  65]
 [ 59 421]]
