# 5. Supervised_Learning_Case_Study - 34

## Case Study

### Objective:



- Practice Naive Bayes algorithm based classification.


- Identify the predictors that can be of influence by experiment.




### Questions:


1. Load the kinematics dataset as measured on mobile sensors from the file “run_or_walk.csv”. List out the columns in the dataset.



2. Let the target variable ‘y’ be the activity and assign all the columns after it to ‘x’.


3. Using Scikit-learn fit a Gaussian Naive Bayes model and observe the accuracy.


4. Generate a classification report using scikit learn.



5. Repeat the model once using only the acceleration values as predictors and then using only the gyro values as predictors. 


6. Comment on the difference in accuracy between both the models.


#### Import Libraries

In [2]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#### Checking directory

In [3]:
os.getcwd()

'C:\\Users\\ankit\\Top_Mentor\\CASE_STUDIES'

#### changing directory

In [4]:
os.chdir('C:\\Users\\ankit\\OneDrive\\Documents\\Desktop\\DATA SCIENCE\\Top Mentor Lecture\\24_Day_31_7_21\\Case Studies with Answer\\CS 34 Ans -Supervised Learnig-5')

#### Loading and printing DataSet

In [5]:
df = pd.read_csv('run_or_walk.csv')
df.head()

date                time username  wrist  activity  acceleration_x  \
0  2017-6-30  13:51:15:847724020   viktor      0         0          0.2650   
1  2017-6-30  13:51:16:246945023   viktor      0         0          0.6722   
2  2017-6-30  13:51:16:446233987   viktor      0         0          0.4399   
3  2017-6-30  13:51:16:646117985   viktor      0         0          0.3031   
4  2017-6-30  13:51:16:846738994   viktor      0         0          0.4814   

   acceleration_y  acceleration_z  gyro_x  gyro_y  gyro_z  
0         -0.7814         -0.0076 -0.0590  0.0325 -2.9296  
1         -1.1233         -0.2344 -0.1757  0.0208  0.1269  
2         -1.4817          0.0722 -0.9105  0.1063 -2.4367  
3         -0.8125          0.0888  0.1199 -0.4099 -2.9336  
4         -0.9312          0.0359  0.0527  0.4379  2.4922

#### Checking data

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88588 entries, 0 to 88587
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   date            88588 non-null  object 
 1   time            88588 non-null  object 
 2   username        88588 non-null  object 
 3   wrist           88588 non-null  int64  
 4   activity        88588 non-null  int64  
 5   acceleration_x  88588 non-null  float64
 6   acceleration_y  88588 non-null  float64
 7   acceleration_z  88588 non-null  float64
 8   gyro_x          88588 non-null  float64
 9   gyro_y          88588 non-null  float64
 10  gyro_z          88588 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 7.4+ MB


In [7]:
df.columns

Index(['date', 'time', 'username', 'wrist', 'activity', 'acceleration_x',
       'acceleration_y', 'acceleration_z', 'gyro_x', 'gyro_y', 'gyro_z'],
      dtype='object')

### Spliting Data into X and y

In [32]:
X = df.iloc[:,5:].values
X[0:5]

array([[ 0.4399, -1.4817,  0.0722, -0.9105,  0.1063, -2.4367],
       [ 0.3031, -0.8125,  0.0888,  0.1199, -0.4099, -2.9336],
       [ 0.4814, -0.9312,  0.0359,  0.0527,  0.4379,  2.4922],
       [ 0.4044, -0.8056, -0.0956,  0.6925, -0.2179,  2.575 ],
       [ 0.632 , -1.129 , -0.2982,  0.0548, -0.1896,  0.4473]])

In [33]:
y = df['activity'].values
y[0:5]

array([0, 0, 0, 0, 0], dtype=int64)

### Train Test Split

In [34]:
from sklearn.model_selection import train_test_split
 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [35]:
print(X_train.shape)
print(y_test.shape)

(70868, 6)
(17718,)


### Creat Model Gaussian Naive Bayes

In [36]:
from sklearn.naive_bayes import GaussianNB

classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

### Prediction

In [37]:
y_pred = classifier.predict(X_test)
y_pred[0:5]

array([1, 0, 0, 1, 1], dtype=int64)

### Accuracy Score

In [38]:
from sklearn.metrics import accuracy_score

In [39]:
accuracy = accuracy_score(y_pred, y_test)
accuracy

0.9567671294728525

### Confussion Matrix

In [40]:
from sklearn.metrics import confusion_matrix

In [65]:
con_mat = confusion_matrix(y_test, y_pred)
print(con_mat)

[[8671   69]
 [ 697 8281]]


### Classification report

In [42]:
from sklearn.metrics import classification_report

In [85]:
target_names = ["Walk","Run"]
class_report = classification_report(y_test, y_pred, target_names = target_names)
print(class_report)

              precision    recall  f1-score   support

        Walk       0.93      0.99      0.96      8740
         Run       0.99      0.92      0.96      8978

    accuracy                           0.96     17718
   macro avg       0.96      0.96      0.96     17718
weighted avg       0.96      0.96      0.96     17718



In [46]:
df.columns

Index(['date', 'time', 'username', 'wrist', 'activity', 'acceleration_x',
       'acceleration_y', 'acceleration_z', 'gyro_x', 'gyro_y', 'gyro_z'],
      dtype='object')

### Train Test Split using only acceleration values as predictor

In [47]:
X1 = df.iloc[: ,5:8].values
X1[0:5]

array([[ 0.4399, -1.4817,  0.0722],
       [ 0.3031, -0.8125,  0.0888],
       [ 0.4814, -0.9312,  0.0359],
       [ 0.4044, -0.8056, -0.0956],
       [ 0.632 , -1.129 , -0.2982]])

In [48]:
y1 = df['activity']
y1[0:5]

2    0
3    0
4    0
5    0
6    0
Name: activity, dtype: int64

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size = 0.2, random_state = 1)
print(X1_train.shape)
print(y1_train.shape)

(70868, 3)
(70868,)


### Creat Model Gaussian NB

In [51]:
from sklearn.naive_bayes import GaussianNB

In [52]:
classifier1 = GaussianNB()
classifier1.fit(X1_train, y1_train)

GaussianNB()

### Prediction

In [57]:
y1_pred = classifier1.predict(X1_test)
print(y1_pred)

[1 0 0 ... 1 0 1]


### Accuracy score

In [58]:
from sklearn.metrics import accuracy_score

In [62]:
accuracy1 = accuracy_score(y1_test, y1_pred)
accuracy1

0.9584603228355345

### Confusion matrix

In [61]:
from sklearn.metrics import confusion_matrix

In [64]:
con_mat1 = confusion_matrix(y1_test, y1_pred)
print(con_mat1)

[[8687   53]
 [ 683 8295]]


### Classification report

In [66]:
from sklearn.metrics import classification_report

In [86]:
target_names = ["Walk","Run"]
class_report1 = classification_report(y1_test, y1_pred, target_names = target_names)
print(class_report1)

              precision    recall  f1-score   support

        Walk       0.93      0.99      0.96      8740
         Run       0.99      0.92      0.96      8978

    accuracy                           0.96     17718
   macro avg       0.96      0.96      0.96     17718
weighted avg       0.96      0.96      0.96     17718



### Train Test Split using only the gyro values as predictors.

In [70]:
X2 = df.iloc[:,8:].values
X2[0:5]

array([[-0.9105,  0.1063, -2.4367],
       [ 0.1199, -0.4099, -2.9336],
       [ 0.0527,  0.4379,  2.4922],
       [ 0.6925, -0.2179,  2.575 ],
       [ 0.0548, -0.1896,  0.4473]])

In [71]:
y2 = df['activity'].values
y2[0:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [73]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size = 0.2, random_state = 1)
print(X2_train.shape)
print(y2_train.shape)

(70868, 3)
(70868,)


### Creat model GaussianNB

In [74]:
from sklearn.naive_bayes import GaussianNB

In [75]:
classifier2 = GaussianNB()
classifier2.fit(X2_train, y2_train)

GaussianNB()

In [76]:
y2_pred = classifier2.predict(X2_test)
print(y2_pred)

[0 0 0 ... 0 0 0]


### Accuracy score

In [77]:
from sklearn.metrics import accuracy_score 

In [78]:
accuracy2 = accuracy_score(y2_test, y2_pred)
accuracy2

0.6421153629077774

### Confussion metrics

In [79]:
from sklearn.metrics import confusion_matrix

In [81]:
con_mat2 = confusion_matrix(y2_test, y2_pred)
print(con_mat2)

[[6512 2228]
 [4113 4865]]


### Classification Report

In [82]:
from sklearn.metrics import classification_report

In [87]:
target_names = ["Walk","Run"]
class_report2 = classification_report(y2_test,y2_pred, target_names = target_names)
print(class_report2)

              precision    recall  f1-score   support

        Walk       0.61      0.75      0.67      8740
         Run       0.69      0.54      0.61      8978

    accuracy                           0.64     17718
   macro avg       0.65      0.64      0.64     17718
weighted avg       0.65      0.64      0.64     17718

